apiVersion: apps/v1
kind: Deployment
metadata:
  name: fondfolio-bot-deployment
spec:
  selector:
    matchLabels:
      app: fondfolio-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: fondfolio-bot
        env: development
    spec:
      containers:
        - name: my-app
          image: gcr.io/fondfolio-bot/app:v1
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: '4000'
            - name: LOG_LEVEL
              value: 'info'
            - name: NODE_ENV
              value: 'development'
---
apiVersion: v1
kind: Service
metadata:
  name: fondfolio-bot-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  selector:
    app: fondfolio-bot
